var baseURL = '../../';
var gnb = {
    menu: function () {
        document.write('<div class="header_menu">');
        document.write('<button type="button" class="btn_menu">');
        document.write('<span class="a11y">메뉴열기</span>');
        document.write('</button>');
        document.write('</div>');
        document.write('<div class="gnb_menu_wrap">');
        document.write('<div class="info_wrap">');
        document.write('<div class="info_header">');
        document.write('<!-- 로그인 전 -->');
        document.write('<!-- <div class="user_info">');
        document.write('<div class="user_profile">');
        document.write('<img src="../../img/my/img_profile_default.png" alt="">');
        document.write('</div>');
        document.write('<div class="user_id">');
        document.write('<a href="#none"><span>로그인을 해주세요.</span></a>');
        document.write('</div>');
        document.write('</div> -->');
        document.write('<!--// 로그인 전 -->');
        document.write('<!-- 로그인 후 -->');
        document.write('<div class="user_info">');
        document.write('<div class="user_profile">');
        document.write('<img src="../../img/my/img_user_profile.png" alt="">');
        document.write('</div>');
        document.write('<div class="user_id">');
        document.write('<p>olivia</p>');
        document.write('<span>dregw9872@naver.com</span>');
        document.write('</div>');
        document.write('</div>');
        document.write('<!--// 로그인 후 -->');
        document.write('<a href="#none" class="info_setting"><i class="ico_setting"><span class="a11y">정보수정</span></i></a>');
        document.write('</div>');
        document.write('<div class="inner_wrap">');
        document.write('<!-- 로그인 전 -->');
        document.write('<!-- <div class="ddp_wrap">');
        document.write('<p class="tit">잔액</p>');
        document.write('<div class="my_point"><p><span>0</span>ddp</p></div>');
        document.write('<div class="bot_area">');
        document.write('<a href="#none" class="charge"><span>충전하기</span><i class="ico_arr_right_purple"></i></a>');
        document.write('<p class="money"><span>0</span>원</p>');
        document.write('</div>');
        document.write('</div> -->');
        document.write('<!--// 로그인 전 -->');
        document.write('<!-- 로그인 후 -->');
        document.write('<div class="ddp_wrap">');
        document.write('<p class="tit">잔액</p>');
        document.write('<div class="my_point"><p><span>561</span>ddp</p></div>');
        document.write('<div class="bot_area">');
        document.write('<a href="#none" class="charge"><span>충전하기</span><i class="ico_arr_right_purple"></i></a>');
        document.write('<p class="money"><span>571,000</span>원</p>');
        document.write('</div>');
        document.write('</div>');
        document.write('<!--// 로그인 후 -->');
        document.write('<div class="gnb_list_wrap">');
        document.write('<div class="gnb_tit">');
        document.write('<h4 class="tit">My order</h4>');
        document.write('</div>');
        document.write('<ul class="order_list">');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<div class="icon">');
        document.write('<img src="../../img/my/ico_my_nft.png" alt="">');
        document.write('</div>');
        document.write('<span>MY NFT</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<div class="icon">');
        document.write('<img src="../../img/my/ico_my_ddp.png" alt="">');
        document.write('</div>');
        document.write('<span>MY DDP</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<div class="icon">');
        document.write('<img src="../../img/my/ico_like.png" alt="">');
        document.write('</div>');
        document.write('<span>관심 상품</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<div class="icon">');
        document.write('<img src="../../img/my/ico_payment.png" alt="">');
        document.write('</div>');
        document.write('<span>결제/인출내역</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<div class="icon">');
        document.write('<img src="../../img/my/ico_breakdown.png" alt="">');
        document.write('</div>');
        document.write('<span>거래 내역</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('</ul>');
        document.write('</div>');
        document.write('<div class="gnb_list_wrap">');
        document.write('<div class="gnb_tit">');
        document.write('<h4 class="tit">Notice</h4>');
        document.write('</div>');
        document.write('<ul class="notice_list">');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<span>이벤트/공지</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<span>자주하는 질문</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<span>고객센터</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<span>아이튜버 NFT란?</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('</ul>');
        document.write('</div>');
        document.write('<!-- 로그인 후 -->');
        document.write('<!-- 로그아웃 버튼 -->');
        document.write('<div class="logout_btn">');
        document.write('<a href="#none">');
        document.write('<i class="ico_logout"></i><span>Logout</span>');
        document.write('</a>');
        document.write('</div>');
        document.write('<!--// 로그인 후 -->');
        document.write('</div>');
        document.write('</div>');
        document.write('</div>');
    }
}
var include = {
    meta : function(){
        document.write('<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>');
        document.write('<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no"/>');
        document.write('<meta name="format-detection" content="telephone=no"/>');
    },
    styles : function(){
        document.write('<link rel="stylesheet" href="'+baseURL+'css/global.css">');
        document.write('<link rel="stylesheet" href="'+baseURL+'css/content.css">');
    },
    scripts : function(){
        document.write('<script type="text/javascript" src="'+baseURL+'js/jquery-3.6.0.min.js"></script>');
        document.write('<script type="text/javascript" src="'+baseURL+'js/common.js"></script>');
    },
    skipNav : function(){
        document.write('<div class="skip_navi"><a href="#gnb">주요 메뉴 바로가기</a><a href="#contents">본문 컨텐츠 바로가기</a></div>');
    },
    header : function(gnbOn){
        document.write('<header class="header">');
        document.write('<div class="header_wrap">');
        document.write('<div class="header_inner">');
        document.write('<div class="header_title">');
        document.write('<a href="#none" class="btn_back">');
        document.write('<i class="ico_arr_left">');
        document.write('<span class="a11y">뒤로가기</span>');
        document.write('</i>');
        document.write('</a>');
        document.write('<h2 class="page_title">'+document.title.split('|')[0]+'</h2>');
        document.write('</div>');
        if (gnbOn == gnb) {
            gnb.menu();
        }
        document.write('</div>');
        document.write('</div>');
        document.write('</header>');
    },
    fixBottom : function(){
        document.write('<div class="fixed_bottom_area">');
        document.write('<div class="fixed_item">');
        document.write('<button type="button" class="btn_gotop">');
        document.write('<i class="ico_arr_up"></i>');
        document.write('<span>TOP</span>');
        document.write('</button>');
        document.write('</div>');
        document.write('</div>');
    },
    footer : function(){
        document.write('<footer class="footer">');
        document.write('<div class="footer_inner">');
        document.write('<div class="footer_head">');
        document.write('<div class="office_name">');
        document.write('<p>I-TUBER NFT</p>');
        document.write('</div>');
        document.write('<div class="footer_btn_wrap">');
        document.write('<ul class="sns_btns">');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<i class="ico_sns_facebook"></i>');
        document.write('<span class="a11y">페이스북 바로가기</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<i class="ico_sns_instagram"></i>');
        document.write('<span class="a11y">인스타그램 바로가기</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<i class="ico_sns_youtube"></i>');
        document.write('<span class="a11y">유튜브 바로가기</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('</ul>');
        document.write('</div>');
        document.write('</div>');
        document.write('<div class="footer_info">');
        document.write('<div class="footer_address_wrap">');
        document.write('<ul class="footer_sort_list">');
        document.write('<li>');
        document.write('<span class="tit">주소</span>');
        document.write('<span class="txt">서울시 마포구 토정로 194 (두리번)</span>');
        document.write('</li>');
        document.write('<li>');
        document.write('<span class="tit">TEL</span>');
        document.write('<span class="txt">+82)02-6395-3926</span>');
        document.write('</li>');
        document.write('<li>');
        document.write('<span class="tit">FAX</span>');
        document.write('<span class="txt">+82)02-6395-3926</span>');
        document.write('</li>');
        document.write('<li>');
        document.write('<span class="tit">E-mail</span>');
        document.write('<span class="txt">i-tuber@dooribun.com</span>');
        document.write('</li>');
        document.write('</ul>');
        document.write('</div>');
        document.write('<div class="footer_licence">');
        document.write('<ul class="footer_sort_list">');
        document.write('<li>');
        document.write('<span class="tit">사업자등록번호</span>');
        document.write('<span class="txt">468-81-00729</span>');
        document.write('</li>');
        document.write('<li>');
        document.write('<span class="tit">통신판매업신고번호</span>');
        document.write('<span class="txt">제2013-SEOUL MAPO-0418</span>');
        document.write('</li>');
        document.write('</ul>');
        document.write('</div>');
        document.write('<div class="footer_menu">');
        document.write('<ul class="footer_menu_list">');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<span>개인정보처리방침</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<span>이메일주소무단수집거부</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('<li>');
        document.write('<a href="#none">');
        document.write('<span>이용약관</span>');
        document.write('</a>');
        document.write('</li>');
        document.write('</ul>');
        document.write('<p class="copy">');
        document.write('Copyright (c) 2022 DOORIBUN All Rights Reserved');
        document.write('</p>');
        document.write('</div>');
        document.write('</div>');
        document.write('</div>');
        document.write('</footer>');
    },
}